default:
  image: node

build-job:
  stage: build
  script:
    - npm install

test-check-code:
  stage: test
  script:
    - npm run lint
    - npm run format:check

test:
  stage: test
  script:
    - npm test